version: '2.1'
services:
  keycloak:
    image: jboss/keycloak:4.5.0.Final
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - DB_VENDOR=H2
    expose:
    - 8080
    command:
    - "-b 0.0.0.0"
    - "-Dkeycloak.import=/opt/jboss/keycloak/gate-opener-realm.json"
    ports:
    - "8080:8080"
    volumes:
    - ./env/keycloak/gate-opener-realm.json:/opt/jboss/keycloak/gate-opener-realm.json